### ISSUE TITLE
eband_local_planner lack of documentation

### ISSUE THREAD

**Issue by raflef11** [utexas-bwi/eband_local_planner#20]
Hello !
I didn't find anywhere a documentation about the list of available parameters for the eband_local_planner.
It would be nice if anyone can provide it.
Thanks.

**Comment by jack-oquin** [comment]
+1

**Comment by piyushk** [comment]
@raflef11: I'll see what I can do, but it might be a couple of weeks before I can get this documentation up. The most important parameters are in eband_trajectory_controller_ros.cpp.

**Comment by jack-oquin** [comment]
@piyushk: maybe one of the summer students could write something up from reading the code.

**Comment by piyushk** [comment]
@jack-oquin: I've tried getting students to read through that code over the years, but it's a tough piece. I've never seen progress.

**Comment by raflef11** [comment]
@piyushk Thank you for your help. I found parameters I needed in eband_trajectory_controller.cpp.

I think that the list of parameters could be displayed in the ros web page for the eband_local_planner (like the others planners). It is more convenient.

Thanks again

**Comment by jack-oquin** [comment]
@raflef11: please let us know if ``differential_drive=false`` works for you.

**Comment by jack-oquin** [comment]
I made a start at listing [some of the ROS parameters](http://wiki.ros.org/eband_local_planner#ROS_Interface). Many of the others would require guess-work on my part.

@piyushk: Please verify or correct my guess that the parameter namespace would be: ``~/eband_local_planner``.

**Comment by raflef11** [comment]
@jack-oquin Yes, for me `differential_drive=false` works properly.

**Comment by jack-oquin** [comment]
> But I have a problem: the parameters does not appear in the parameter server (when I type rosparam list there is no result for the eband_local_planner).

How did you set them?

**Comment by raflef11** [comment]
I created a YAML file which contains the following lines:
```
EBandPlannerROS:

  differential_drive: false
  rotation_correction_threshold: 1.0
```
Then, I load it through a launch file as follows:
`<rosparam file="$(find my_package)/config/eb_planner.yaml" command="load" />`

**Comment by jack-oquin** [comment]
What does this command print?
```
rosparam list | grep differential
```

**Comment by raflef11** [comment]
I already tried this command but it return nothing

**Comment by raflef11** [comment]
Oh, it's good, I don't know what I changed but it works now, thank you

**Comment by jack-oquin** [comment]
@raflef11: What was the full name of your parameter?

I am wondering whether the documentation I wrote is correct.

**Comment by raflef11** [comment]
The full names of the parameters I use are:
```
/move_base/EBandPlannerROS/differential_drive
/move_base/EBandPlannerROS/rotation_correction_threshold
```

**Comment by jack-oquin** [comment]
So, ``EBandPlannerROS`` is the name under which you configured the ``base_local_planner``?

That means my documentation is wrong. I thought it would be ``eband_local_planner``.

**Comment by raflef11** [comment]
Yes, I used `EBandPlannerROS` as you can see above (where I wrote the YAML file content). The documentation is effectively wrong ;)

**Comment by jack-oquin** [comment]
I think it's better now. Please check, and comment here if it's still wrong.

**Comment by raflef11** [comment]
It seems to be good

**Comment by jack-oquin** [comment]
Thanks for your help.

**Comment by raflef11** [comment]
You likewise.
