### ISSUE TITLE
ROS Melodic Morenia release

### ISSUE THREAD

**Issue by AchmadFathoni** [utexas-bwi/eband_local_planner#28]
I am really need this package for my robot. Unfortunately I plan to upgrade my robot to ROS Melodic Morenia soon. Would you kindly release the compatible version?

**Comment by mintar** [comment]
+1 for releasing into Melodic. Unfortunately, this is blocked by the navigation stack: https://github.com/ros-planning/navigation/issues/749

Until that ticket is resolved, nothing can be done here.

**Comment by mintar** [comment]
Navigation has been released and synced. Could you please release eband_local_planner for lunar and melodic? No changes should be necessary, just a bloom release.

**Comment by saikishor** [comment]
@mintar do you have any idea, when it is going to be released in Melodic ?

**Comment by mintar** [comment]
The maintainers seem to have abandoned this repo. I have switched away from it, I'm using dwb_local_planner now.

**Comment by spuetz** [comment]
Hi @zhuyifengzju any plans for releasing eband_local_planner for Melodic? Cheers.

**Comment by maxsvetlik** [comment]
An update on this: I am affiliated with the same lab as the previous maintainers (Piyush and Jack) and am working on releasing this (and other UTexas packages) for Melodic. Apologies in the delay, but the Noetic release will be much more timely!

Stay tuned.

**Comment by ajaypaul2008** [comment]
@maxsvetlik any migration plans for ROS2?

**Comment by maxsvetlik** [comment]
@ajaypaul2008 not at this time.

**Comment by maxsvetlik** [comment]
Release [0.4.0](https://github.com/utexas-bwi/eband_local_planner/releases/tag/0.4.0) targets ROS Melodic. Package release into ROS ecosystem is coming.

**Comment by maxsvetlik** [comment]
Binaries are now released for Melodic / Bionic! Thank you for your patience.

**Comment by juliangaal** [comment]
> An update on this: I am affiliated with the same lab as the previous maintainers (Piyush and Jack) and am working on releasing this (and other UTexas packages) for Melodic. Apologies in the delay, but the Noetic release will be much more timely!
> 
> Stay tuned.

Any update on noetic? Cheers

**Comment by gglaspell** [comment]
second, on noetic release

**Comment by saikishor** [comment]
+1
